# fpga_top.xdc -- constraints for fpga_top.v.
#
# NO manual pin constraints (PACKAGE_PIN/IOSTANDARD) belong in this file.
# Confirmed by inspecting the working zynq_tut Hello World project
# (D:/Vivado_Projects/zynq_tut): it has ZERO hand-written .xdc files
# anywhere -- UART1 (MIO48/49), DDR, and FIXED_IO were ALL auto-generated
# by Vivado from the ZC702 board preset applied to the processing_system7
# IP in the block design. Once fpga_top is instantiated as an RTL module
# inside that same block design (see build_zynq_bd.tcl), clk_i/rst_i stop
# being top-level physical ports at all -- they connect to PS7's
# FCLK_CLK0/FCLK_RESET0_N internally. design_1_wrapper (generated by
# Vivado from the block design) becomes the real top level, and its only
# physical ports are PS7's DDR/FIXED_IO, which the board preset already
# constrains. Do not hand-type pin numbers here -- that would risk
# contradicting the auto-generated, already-hardware-proven constraints.

# NOTE: no create_clock here. Once fpga_top is instantiated inside the
# zynq_system block design, clk_i/rst_i are internal pins, not top-level
# ports -- a create_clock targeting [get_ports clk_i] silently fails to
# match anything (confirmed: "[Vivado 12-584] No ports matched 'clk_i'"
# in the impl log) and is never actually applied. The real clock
# definition for FCLK_CLK0 (what clk_i is driven from) is auto-generated
# by the processing_system7 IP itself, straight from its
# CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR0/1 properties -- set those in
# build_zynq_bd.tcl (or directly on processing_system7_0) instead of
# hand-writing a clock constraint here; it would just be dead weight.
#
# rst_i is asynchronous by design (see fpga_top.v's reset synchronizer).
# Same top-level-port problem as clk_i above -- [get_ports rst_i] no
# longer matches once PS7 exists. Confirmed via
# `get_pins -hierarchical -filter {NAME =~ "*rst_i"}` in the Tcl console:
# the real hierarchical pin is zynq_system_i/fpga_top_0/inst/rst_i.
set_false_path -from [get_pins -quiet zynq_system_i/fpga_top_0/inst/rst_i]
