#!/usr/bin/env python3
"""
elf2hex.py -- convert a linked RISC-V ELF into the exact $readmemh format
axi4_bram_slave.v expects (one 64-bit hex word per line, `@<word_index>`
markers between non-contiguous regions), replacing the hand-spliced
boot_image.hex this repo previously maintained by hand.

Word indexing matches axi4_bram_slave.v's widx() exactly:
    widx(addr) = addr[15:3]   (MEM_WORDS=8192 -> 13-bit index, 8 bytes/word)
i.e. idx = (addr & 0xFFFF) >> 3 -- this script must stay in sync with that
function if MEM_WORDS or the address width ever changes there.

Packing within a word matches the hand-assembled convention already
verified in tb_cva6_boot.v/boot_image.hex: word[31:0] = the instruction at
the word's base address, word[63:32] = the instruction 4 bytes later. This
falls out naturally from reading each section's raw little-endian bytes
(standard RISC-V instruction encoding) 8 bytes at a time as one
little-endian 64-bit integer -- no manual byte-swapping needed.

Usage:
    python3 elf2hex.py boot_matmul.elf boot_image.hex [--cross-prefix riscv64-unknown-elf-]
"""
import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

WORD_BYTES = 8
MEM_WORDS = 8192           # must match axi4_bram_slave.v's MEM_WORDS parameter
IDX_MASK = 0xFFFF           # addr[15:3] -> mask to 16 bits before shifting


def widx(addr: int) -> int:
    return (addr & IDX_MASK) >> 3


def run(cmd):
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(f"command failed: {' '.join(cmd)}\n{result.stderr}\n")
        sys.exit(1)
    return result.stdout


def section_info(cross_prefix: str, elf_path: str):
    """Return [(name, vma, size), ...] for allocatable sections, via objdump -h."""
    out = run([f"{cross_prefix}objdump", "-h", elf_path])
    sections = []
    for line in out.splitlines():
        parts = line.split()
        # objdump -h line shape: idx name size vma lma file_off algn
        if len(parts) >= 7 and parts[0].isdigit():
            name = parts[1]
            size = int(parts[2], 16)
            vma = int(parts[3], 16)
            if size > 0 and (name == ".text" or name == ".matrix"):
                sections.append((name, vma, size))
    return sections


def extract_bytes(cross_prefix: str, elf_path: str, section: str, size: int) -> bytes:
    with tempfile.NamedTemporaryFile(delete=False, suffix=".bin") as tf:
        tmp = tf.name
    run([f"{cross_prefix}objcopy", "-O", "binary", f"--only-section={section}", elf_path, tmp])
    data = Path(tmp).read_bytes()
    Path(tmp).unlink(missing_ok=True)
    if len(data) < size:
        data = data + b"\x00" * (size - len(data))
    return data[:size]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("elf")
    ap.add_argument("out_hex")
    ap.add_argument("--cross-prefix", default="riscv64-unknown-elf-")
    args = ap.parse_args()

    sections = section_info(args.cross_prefix, args.elf)
    if not sections:
        sys.stderr.write("no non-empty .text/.matrix sections found -- check the ELF and objdump output\n")
        sys.exit(1)

    lines = [
        "// Generated by elf2hex.py from a real riscv64-unknown-elf-gcc/ld build",
        "// (boot_matmul.S + link.ld) -- replaces the hand-spliced boot_image.hex.",
        "// Regenerate via build.sh; do not hand-edit.",
    ]
    for name, vma, size in sections:
        data = extract_bytes(args.cross_prefix, args.elf, name, size)
        start_idx = widx(vma)
        n_words = (size + WORD_BYTES - 1) // WORD_BYTES
        if start_idx + n_words > MEM_WORDS:
            sys.stderr.write(
                f"section {name} (vma=0x{vma:x}, {size} bytes) overflows "
                f"MEM_WORDS={MEM_WORDS} -- check link.ld placement\n"
            )
            sys.exit(1)
        lines.append(f"@{start_idx:x}")
        for i in range(0, len(data), WORD_BYTES):
            chunk = data[i:i + WORD_BYTES]
            word = int.from_bytes(chunk, "little")
            lines.append(f"{word:016x}")

    Path(args.out_hex).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out_hex}: {len(sections)} section(s)")


if __name__ == "__main__":
    main()
