`timescale 1ns / 1ps

// Cycle-count comparison: same CVA6+TinyGPU SoC, same 4x4 matrix A, run
// through TWO independent cold boots back to back --
//
//   Phase 1 (OFFLOAD): CVA6 boots, loads A via vle64.v, issues ONE vmacc.vv
//   (offloaded to TinyGPU over CV-X-IF), and TinyGPU streams the 4x4 result
//   back over its own AXI4 write master. Timed from reset release to the
//   last writeback word landing in memory.
//
//   Phase 2 (SCALAR): the boot memory is overwritten with a plain RV64IM
//   program -- no custom/vector opcodes at all -- that computes the exact
//   same C = A x A on CVA6's own scalar pipeline (16 outputs x 4
//   multiply-accumulates each, straight-line/unrolled, ld+ld+mul+add x4 per
//   output + one sd), using CVA6's M-extension `mul`. The whole SoC is then
//   reset again (a real cold reboot, same DUT instance) and timed the same
//   way, from reset release to its own last store landing.
//
// Both timings use the same $time/CLK_PERIOD arithmetic, so the ratio
// (scalar_cycles / offload_cycles) is a direct, apples-to-apples cycle-count
// speedup of "offload the matmul to TinyGPU" vs. "just run it on CVA6",
// entirely in simulation -- no hardware needed.
//
// The scalar RV64IM program is not hand-encoded like the offload one --
// it's assembled at elaboration time from little encoder functions
// (enc_utype/enc_itype/enc_stype/enc_rtype below), following the standard
// RISC-V bit layouts, and generated by looping over i/j/k in the initial
// block. This is the only practical way to get ~300 correct instructions
// without hand-computing every opcode.
module tb_speedup_cycles;

  localparam integer CLK_PERIOD = 10; // 100 MHz, matches `always #5 clk = ~clk;` below

  localparam [63:0] BOOT_ADDR          = 64'h0000_0000_8000_0000;
  localparam [63:0] MAT_ADDR           = 64'h0000_0000_8000_1000;
  localparam [63:0] MUL_RESULT_ADDR    = 64'h0000_0000_8000_2000; // offload (TinyGPU) writeback
  localparam [63:0] SCALAR_RESULT_ADDR = 64'h0000_0000_8000_5000; // scalar (CVA6-only) writeback

  reg clk = 0;
  reg rst_ni = 0;
  always #5 clk = ~clk; // 100 MHz

  // ---- NOC/AXI4 -- same single shared, arbitrated bus as tb_cva6_boot.v ----
  wire [4:0]  noc_aw_id;   wire [63:0] noc_aw_addr; wire [7:0] noc_aw_len;
  wire [2:0]  noc_aw_size; wire [1:0]  noc_aw_burst;wire       noc_aw_lock;
  wire [3:0]  noc_aw_cache;wire [2:0]  noc_aw_prot; wire [3:0] noc_aw_qos;
  wire [3:0]  noc_aw_region;wire [5:0] noc_aw_atop; wire [63:0]noc_aw_user;
  wire        noc_aw_valid; wire       noc_aw_ready;

  wire [4:0]  noc_ar_id;   wire [63:0] noc_ar_addr; wire [7:0] noc_ar_len;
  wire [2:0]  noc_ar_size; wire [1:0]  noc_ar_burst;wire       noc_ar_lock;
  wire [3:0]  noc_ar_cache;wire [2:0]  noc_ar_prot; wire [3:0] noc_ar_qos;
  wire [3:0]  noc_ar_region;wire [63:0]noc_ar_user;
  wire        noc_ar_valid; wire       noc_ar_ready;

  wire [63:0] noc_w_data;  wire [7:0]  noc_w_strb;  wire       noc_w_last;
  wire [63:0] noc_w_user;  wire        noc_w_valid; wire       noc_w_ready;

  wire [4:0]  noc_b_id;    wire [1:0]  noc_b_resp;  wire [63:0]noc_b_user;
  wire        noc_b_valid; wire        noc_b_ready;

  wire [4:0]  noc_r_id;    wire [63:0] noc_r_data;  wire [1:0] noc_r_resp;
  wire        noc_r_last;  wire [63:0] noc_r_user;
  wire        noc_r_valid; wire        noc_r_ready;

  cva6_tinygpu_soc dut (
    .clk        (clk),
    .rst_ni     (rst_ni),
    .boot_addr  (BOOT_ADDR),
    .hart_id    (64'd0),
    .irq        (2'b00),
    .ipi        (1'b0),
    .time_irq   (1'b0),
    .debug_req  (1'b0),

    .noc_aw_id(noc_aw_id), .noc_aw_addr(noc_aw_addr), .noc_aw_len(noc_aw_len),
    .noc_aw_size(noc_aw_size), .noc_aw_burst(noc_aw_burst), .noc_aw_lock(noc_aw_lock),
    .noc_aw_cache(noc_aw_cache), .noc_aw_prot(noc_aw_prot), .noc_aw_qos(noc_aw_qos),
    .noc_aw_region(noc_aw_region), .noc_aw_atop(noc_aw_atop), .noc_aw_user(noc_aw_user),
    .noc_aw_valid(noc_aw_valid), .noc_aw_ready(noc_aw_ready),

    .noc_ar_id(noc_ar_id), .noc_ar_addr(noc_ar_addr), .noc_ar_len(noc_ar_len),
    .noc_ar_size(noc_ar_size), .noc_ar_burst(noc_ar_burst), .noc_ar_lock(noc_ar_lock),
    .noc_ar_cache(noc_ar_cache), .noc_ar_prot(noc_ar_prot), .noc_ar_qos(noc_ar_qos),
    .noc_ar_region(noc_ar_region), .noc_ar_user(noc_ar_user),
    .noc_ar_valid(noc_ar_valid), .noc_ar_ready(noc_ar_ready),

    .noc_w_data(noc_w_data), .noc_w_strb(noc_w_strb), .noc_w_last(noc_w_last),
    .noc_w_user(noc_w_user), .noc_w_valid(noc_w_valid), .noc_w_ready(noc_w_ready),

    .noc_b_id(noc_b_id), .noc_b_resp(noc_b_resp), .noc_b_user(noc_b_user),
    .noc_b_valid(noc_b_valid), .noc_b_ready(noc_b_ready),

    .noc_r_id(noc_r_id), .noc_r_data(noc_r_data), .noc_r_resp(noc_r_resp),
    .noc_r_last(noc_r_last), .noc_r_user(noc_r_user),
    .noc_r_valid(noc_r_valid), .noc_r_ready(noc_r_ready)
  );

  axi4_mem_slave #(.ID_WIDTH(5), .ADDR_WIDTH(64), .DATA_WIDTH(64)) u_noc_mem (
    .clk(clk), .rst_ni(rst_ni),
    .ar_id(noc_ar_id), .ar_addr(noc_ar_addr), .ar_len(noc_ar_len),
    .ar_valid(noc_ar_valid), .ar_ready(noc_ar_ready),
    .r_id(noc_r_id), .r_data(noc_r_data), .r_resp(noc_r_resp),
    .r_last(noc_r_last), .r_valid(noc_r_valid), .r_ready(noc_r_ready),
    .aw_id(noc_aw_id), .aw_addr(noc_aw_addr),
    .aw_valid(noc_aw_valid), .aw_ready(noc_aw_ready),
    .w_data(noc_w_data), .w_strb(noc_w_strb), .w_last(noc_w_last),
    .w_valid(noc_w_valid), .w_ready(noc_w_ready),
    .b_id(noc_b_id), .b_resp(noc_b_resp), .b_valid(noc_b_valid), .b_ready(noc_b_ready)
  );

  // ==================== Phase 1: offload (vmacc) program ====================
  // Trimmed version of tb_cva6_boot.v's boot program: load A, vmacc (A x A),
  // store C_mul to MUL_RESULT_ADDR, then self-loop -- no vadd.vv, we only
  // care about timing the matmul itself.
  localparam [31:0] I_LUI     = 32'h800010B7; // lui   x1, 0x80001  -> x1 = MAT_ADDR (sign-extended, see below)
  localparam [31:0] I_SLLI32  = 32'h02009093; // slli  x1, x1, 32
  localparam [31:0] I_SRLI32  = 32'h0200D093; // srli  x1, x1, 32   -> x1 = 0x0000000080001000 = MAT_ADDR
  localparam [31:0] I_VLE64   = 32'h0020F007; // vle64.v vs1=1, vs2=2 -- load A into L3 line1, B(=A) into line2
  localparam [31:0] I_VMACC   = 32'hB420A057; // vmacc   vs1=1, vs2=2 -- C_mul = A x A
  localparam [31:0] I_LUI_MUL = 32'h800020B7; // lui   x1, 0x80002 -> x1 = MUL_RESULT_ADDR (same sign-extend pattern)
  localparam [31:0] I_VSE64   = 32'h0000F027; // vse64.v rs1=1 -- write C_mul to x1 = MUL_RESULT_ADDR
  localparam [31:0] I_JAL0    = 32'h0000006F; // jal   x0, 0   -- infinite self-loop (park the core)

  localparam [63:0] D_A00 = 64'd1,  D_A01 = 64'd2,  D_A02 = 64'd3,  D_A03 = 64'd4;
  localparam [63:0] D_A10 = 64'd5,  D_A11 = 64'd6,  D_A12 = 64'd7,  D_A13 = 64'd8;
  localparam [63:0] D_A20 = 64'd9,  D_A21 = 64'd10, D_A22 = 64'd11, D_A23 = 64'd12;
  localparam [63:0] D_A30 = 64'd13, D_A31 = 64'd14, D_A32 = 64'd15, D_A33 = 64'd16;

  task load_offload_program;
    begin
      u_noc_mem.mem[u_noc_mem.widx(BOOT_ADDR)]   = {I_SLLI32,   I_LUI};    // +0x00 lui,      +0x04 slli
      u_noc_mem.mem[u_noc_mem.widx(BOOT_ADDR)+1] = {I_VLE64,    I_SRLI32}; // +0x08 srli,     +0x0c vle64
      u_noc_mem.mem[u_noc_mem.widx(BOOT_ADDR)+2] = {I_LUI_MUL,  I_VMACC};  // +0x10 vmacc,    +0x14 lui_mul
      u_noc_mem.mem[u_noc_mem.widx(BOOT_ADDR)+3] = {I_SRLI32,   I_SLLI32}; // +0x18 slli,     +0x1c srli
      u_noc_mem.mem[u_noc_mem.widx(BOOT_ADDR)+4] = {I_JAL0,     I_VSE64};  // +0x20 vse64.v (writes C_mul), +0x24 jal (self-loop)

      // Matrix A at MAT_ADDR+0..+15; B (=A) at MAT_ADDR+16..+31.
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+0]  = D_A00; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+1]  = D_A01;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+2]  = D_A02; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+3]  = D_A03;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+4]  = D_A10; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+5]  = D_A11;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+6]  = D_A12; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+7]  = D_A13;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+8]  = D_A20; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+9]  = D_A21;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+10] = D_A22; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+11] = D_A23;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+12] = D_A30; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+13] = D_A31;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+14] = D_A32; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+15] = D_A33;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+16] = D_A00; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+17] = D_A01;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+18] = D_A02; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+19] = D_A03;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+20] = D_A10; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+21] = D_A11;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+22] = D_A12; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+23] = D_A13;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+24] = D_A20; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+25] = D_A21;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+26] = D_A22; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+27] = D_A23;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+28] = D_A30; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+29] = D_A31;
      u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+30] = D_A32; u_noc_mem.mem[u_noc_mem.widx(MAT_ADDR)+31] = D_A33;
    end
  endtask

  // ==================== Phase 2: scalar (CVA6-only) program ====================
  // Standard RISC-V encoders (RV64I/M). No custom opcodes used anywhere here.
  function [31:0] enc_utype;
    input [6:0]  opcode;
    input [4:0]  rd;
    input [19:0] imm20;
    begin
      enc_utype = {imm20, rd, opcode};
    end
  endfunction

  function [31:0] enc_itype;
    input [6:0]  opcode;
    input [4:0]  rd;
    input [2:0]  funct3;
    input [4:0]  rs1;
    input [11:0] imm12;
    begin
      enc_itype = {imm12, rs1, funct3, rd, opcode};
    end
  endfunction

  function [31:0] enc_stype;
    input [6:0]  opcode;
    input [2:0]  funct3;
    input [4:0]  rs1;
    input [4:0]  rs2;
    input [11:0] imm12;
    begin
      enc_stype = {imm12[11:5], rs2, rs1, funct3, imm12[4:0], opcode};
    end
  endfunction

  function [31:0] enc_rtype;
    input [6:0] opcode;
    input [2:0] funct3;
    input [6:0] funct7;
    input [4:0] rd;
    input [4:0] rs1;
    input [4:0] rs2;
    begin
      enc_rtype = {funct7, rs2, rs1, funct3, rd, opcode};
    end
  endfunction

  // x1 = MAT_ADDR (reuses the same known-good lui/slli/srli sequence as the
  // offload program above -- MAT_ADDR is identical in both phases).
  // x2 = SCALAR_RESULT_ADDR, built the same way (lui sign-extends since
  // SCALAR_RESULT_ADDR's bit31 is set, so slli/srli x2,x2,32 zero-extends it
  // back down, exactly like x1's setup).
  //
  // These three are plain hex, not enc_utype()/enc_itype() calls: XSim's
  // Verilog-2001 elaborator won't evaluate function calls inside a
  // module-scope localparam declaration (functions are only usable from
  // procedural code below, e.g. inside build_scalar_program). Derived by
  // the same bit layout as I_LUI/I_SLLI32/I_SRLI32 above, just for x2
  // (rd=rs1=2) instead of x1 (rd=rs1=1), and cross-checked to reproduce
  // I_LUI/I_SLLI32/I_SRLI32 exactly when rd/rs1=1 is substituted back in.
  localparam [31:0] I_LUI2     = 32'h80005137; // lui  x2, 0x80005
  localparam [31:0] I_SLLI2_32 = 32'h02011113; // slli x2, x2, 32
  localparam [31:0] I_SRLI2_32 = 32'h02015113; // srli x2, x2, 32  -> x2 = SCALAR_RESULT_ADDR

  // Instruction stream: 6 preamble words (x1/x2 setup) + 16 outputs x 18
  // instructions (zero + 4x[ld,ld,mul,add] + sd) + 1 final self-loop jal.
  localparam integer N_PRE   = 6;
  localparam integer N_PER_OUT = 18;
  localparam integer N_PROG  = N_PRE + 16*N_PER_OUT + 1; // = 295
  localparam integer N_WORDS = (N_PROG + 1) / 2;          // 64-bit words, padded to even

  // Instruction addresses of the first "ld" and last "add" of the whole
  // matmul loop (block-relative offsets: 0=addi zero, 1..16=4x[ld,ld,mul,add],
  // 17=sd -- see build_scalar_program below), used to time JUST the
  // multiply-accumulate work, excluding the x1/x2 address setup preamble
  // and the final sd/AXI writeback.
  localparam integer FIRST_LD_IDX = N_PRE + 1;                    // = 7
  localparam integer LAST_ADD_IDX = N_PRE + 15*N_PER_OUT + 16;    // = 292
  localparam [63:0]  FIRST_LD_ADDR = BOOT_ADDR + FIRST_LD_IDX*4;
  localparam [63:0]  LAST_ADD_ADDR = BOOT_ADDR + LAST_ADD_IDX*4;

  reg [31:0] prog [0:N_WORDS*2-1];

  integer gi, gj, gk, idx;

  task build_scalar_program;
    begin
      idx = 0;
      prog[idx] = I_LUI;       idx = idx + 1; // lui   x1, MAT_ADDR>>12
      prog[idx] = I_SLLI32;    idx = idx + 1; // slli  x1, x1, 32
      prog[idx] = I_SRLI32;    idx = idx + 1; // srli  x1, x1, 32  -> x1 = MAT_ADDR
      prog[idx] = I_LUI2;      idx = idx + 1; // lui   x2, SCALAR_RESULT_ADDR>>12
      prog[idx] = I_SLLI2_32;  idx = idx + 1; // slli  x2, x2, 32
      prog[idx] = I_SRLI2_32;  idx = idx + 1; // srli  x2, x2, 32  -> x2 = SCALAR_RESULT_ADDR

      for (gi = 0; gi < 4; gi = gi + 1) begin
        for (gj = 0; gj < 4; gj = gj + 1) begin
          // x5 = 0 (accumulator)
          prog[idx] = enc_itype(7'b0010011, 5'd5, 3'b000, 5'd0, 12'd0);
          idx = idx + 1;
          for (gk = 0; gk < 4; gk = gk + 1) begin
            // x6 = A[i][k]  (ld x6, ((i*4+k)*8)(x1))
            prog[idx] = enc_itype(7'b0000011, 5'd6, 3'b011, 5'd1, ((gi*4+gk)*8));
            idx = idx + 1;
            // x7 = A[k][j]  (B == A, so also indexed off x1) (ld x7, ((k*4+j)*8)(x1))
            prog[idx] = enc_itype(7'b0000011, 5'd7, 3'b011, 5'd1, ((gk*4+gj)*8));
            idx = idx + 1;
            // x28 = x6 * x7  (RV64M mul: opcode 0110011, funct3 000, funct7 0000001)
            prog[idx] = enc_rtype(7'b0110011, 3'b000, 7'b0000001, 5'd28, 5'd6, 5'd7);
            idx = idx + 1;
            // x5 = x5 + x28
            prog[idx] = enc_rtype(7'b0110011, 3'b000, 7'b0000000, 5'd5, 5'd5, 5'd28);
            idx = idx + 1;
          end
          // sd x5, ((i*4+j)*8)(x2)
          prog[idx] = enc_stype(7'b0100011, 3'b011, 5'd2, 5'd5, ((gi*4+gj)*8));
          idx = idx + 1;
        end
      end

      prog[idx] = I_JAL0; idx = idx + 1; // self-loop, parks the core

      // Pad to an even instruction count with nops so the 64-bit packing
      // below always has a matching upper half.
      if (idx % 2 != 0) begin
        prog[idx] = 32'h00000013; // addi x0,x0,0 (nop), unreachable pad
        idx = idx + 1;
      end

      for (gi = 0; gi < idx/2; gi = gi + 1) begin
        u_noc_mem.mem[u_noc_mem.widx(BOOT_ADDR)+gi] = {prog[2*gi+1], prog[2*gi]};
      end

      // Matrix A must still be resident at MAT_ADDR -- it is (mem[] is not
      // cleared by reset), so no need to reload it here.
    end
  endtask

  // ==================== Timing ====================
  real t_reset_release, t_offload_done, t_scalar_start, t_scalar_done;
  integer offload_cycles, scalar_cycles;
  real speedup;

  // "Matmul-only" windows -- TinyGPU: FSM entering COMPUTE (cache load/L3
  // write already done) to result_valid (last pass latched), no vle64/vse64
  // AXI time included. CVA6: first matmul "ld" commit to last matmul "add"
  // commit, no x1/x2 setup or final sd/AXI-store time included.
  real t_offload_compute_start, t_offload_compute_end;
  real t_scalar_compute_start, t_scalar_compute_end;
  integer offload_compute_cycles, scalar_compute_cycles;
  real compute_speedup;

  initial begin
    // ---------------- Phase 1: offload ----------------
    load_offload_program;

    rst_ni = 1'b0;
    repeat (10) @(posedge clk);
    rst_ni = 1'b1;
    @(posedge clk);
    t_reset_release = $time;
    $display("[%0t] Phase 1 (OFFLOAD): reset released, CVA6 booting from 0x%h", $time, BOOT_ADDR);

    // ---- matmul-only window (TinyGPU side): state enters COMPUTE only
    // after the vle64 cache-fill + L3 write have already completed, and
    // result_valid marks the instant the last pass (dot_reg[3]) is latched
    // -- this excludes the AXI load AND the AXI writeback entirely.
    while (dut.u_gpu.fsm_i.state !== 3'd4) @(posedge clk); // COMPUTE = 3'd4
    t_offload_compute_start = $time;
    while (!dut.u_gpu.fsm_i.result_valid) @(posedge clk);
    t_offload_compute_end = $time;
    offload_compute_cycles = $rtoi((t_offload_compute_end - t_offload_compute_start) / CLK_PERIOD);
    $display("[%0t] TinyGPU matmul-only (COMPUTE state entered -> result_valid): %0d cycles.",
              $time, offload_compute_cycles);

    // vmacc writeback is a 16-beat AXI4 burst, strictly in order -- once the
    // LAST word (C_mul[3][3] = 600) lands, the whole result is in memory.
    while (u_noc_mem.mem[u_noc_mem.widx(MUL_RESULT_ADDR)+15] !== 64'd600) @(posedge clk);
    t_offload_done = $time;
    offload_cycles = $rtoi((t_offload_done - t_reset_release) / CLK_PERIOD);
    $display("[%0t] Phase 1 done -- offload (TinyGPU vmacc) matmul took %0d cycles.",
              $time, offload_cycles);

    // ---------------- Phase 2: scalar ----------------
    build_scalar_program;

    rst_ni = 1'b0;
    repeat (10) @(posedge clk);
    rst_ni = 1'b1;
    @(posedge clk);
    t_scalar_start = $time;
    $display("[%0t] Phase 2 (SCALAR): reset released, CVA6 booting from 0x%h", $time, BOOT_ADDR);

    // ---- matmul-only window (CVA6 side): first matmul "ld" commit to last
    // matmul "add" commit -- excludes the x1/x2 lui/slli/srli address setup
    // preamble AND the final sd + AXI writeback. commit_ack_commit_id[0] +
    // pc_commit are commit_stage_i's own ports, wired straight up to
    // cva6.sv's top level, so this doesn't depend on which register-file
    // variant (FPGA vs. ASIC) got selected.
    while (!(dut.u_shim.u_cva6.commit_ack_commit_id[0] &&
             dut.u_shim.u_cva6.pc_commit == FIRST_LD_ADDR)) @(posedge clk);
    t_scalar_compute_start = $time;
    while (!(dut.u_shim.u_cva6.commit_ack_commit_id[0] &&
             dut.u_shim.u_cva6.pc_commit == LAST_ADD_ADDR)) @(posedge clk);
    t_scalar_compute_end = $time;
    scalar_compute_cycles = $rtoi((t_scalar_compute_end - t_scalar_compute_start) / CLK_PERIOD);
    $display("[%0t] CVA6 matmul-only (first ld commit -> last add commit): %0d cycles.",
              $time, scalar_compute_cycles);

    while (u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+15] !== 64'd600) @(posedge clk);
    t_scalar_done = $time;
    scalar_cycles = $rtoi((t_scalar_done - t_scalar_start) / CLK_PERIOD);
    $display("[%0t] Phase 2 done -- scalar (CVA6-only) matmul took %0d cycles.",
              $time, scalar_cycles);

    // Print the actual computed result matrix out of memory (not an
    // internal GPU signal -- SCALAR_RESULT_ADDR is written purely by CVA6's
    // own `sd` instructions), same 4x4 layout as tb_cva6_boot.v's C_mul
    // printout, so it's directly diffable against the expected A x A result.
    $display("Scalar (CVA6-only) result C_scalar (read directly out of DRAM at SCALAR_RESULT_ADDR):");
    $display("  %0d %0d %0d %0d",
        u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+0], u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+1],
        u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+2], u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+3]);
    $display("  %0d %0d %0d %0d",
        u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+4], u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+5],
        u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+6], u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+7]);
    $display("  %0d %0d %0d %0d",
        u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+8], u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+9],
        u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+10], u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+11]);
    $display("  %0d %0d %0d %0d",
        u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+12], u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+13],
        u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+14], u_noc_mem.mem[u_noc_mem.widx(SCALAR_RESULT_ADDR)+15]);
    $display("Expected (same A x A as the offload phase):");
    $display("  90 100 110 120");
    $display("  202 228 254 280");
    $display("  314 356 398 440");
    $display("  426 484 542 600");

    speedup = scalar_cycles * 1.0 / offload_cycles;
    compute_speedup = scalar_compute_cycles * 1.0 / offload_compute_cycles;

    $display("");
    $display("==================== 4x4 matmul cycle-count summary ====================");
    $display("  Offload to TinyGPU (vmacc.vv) : %0d cycles  [full path: reset->writeback]", offload_cycles);
    $display("  Scalar on CVA6 (RV64IM, mul)  : %0d cycles  [full path: reset->writeback]", scalar_cycles);
    $display("  Speedup (scalar / offload)    : %0.2fx  (full path)", speedup);
    $display("");
    $display("  -- matmul-only (no boot/fetch, no load/store AXI) --");
    $display("  TinyGPU compute (COMPUTE->result_valid) : %0d cycles", offload_compute_cycles);
    $display("  CVA6 compute (first ld->last add commit): %0d cycles", scalar_compute_cycles);
    $display("  Speedup (matmul-only)                   : %0.2fx", compute_speedup);
    $display("==========================================================================");

    repeat (20) @(posedge clk);
    $finish;
  end

  initial begin
    #400000;
    $display("[%0t] TIMEOUT -- one of the two phases never completed.", $time);
    $finish;
  end

endmodule
